# Workflow
name: Build Pull Request

env:
  SLN_PATH: Source/

on:
  workflow_dispatch:
    inputs:
      PR:
        description: PR Number
        required: true
  pull_request_target:
    branches: [ master ]

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    # Check Repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Setup .NET
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x    

    # Build Mod
    - name: Build Mod
      run: |
        dotnet restore ${{ env.SLN_PATH }}
        dotnet build ${{ env.SLN_PATH }} --configuration Debug --no-restore
        
    # Pack Build
    - name: Package Build
      run: |
        mkdir CombatOverhaul
        cp -r About/ Assemblies/ Defs/ Languages/ Patches/ Royalty/ Ideology/ Sounds/ Source/ Textures/ LoadFolders.xml README.md SupportedThirdPartyMods.md CombatOverhaul
        zip -9 -r CombatOverhaul.zip CombatOverhaul
    
    # Upload Package
    - name: Upload Package
      uses: actions/upload-artifact@v2
      with:
        name: CombatOverhaul
        path: CombatOverhaul.zip
          
    # Create Comment
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}${{ github.event.inputs.PR }}
        body: |
          You can download the built mod for this PR here: 
          https://github.com/CombatOverhaul/CombatOverhaul/actions/runs/${{github.run_id}}
    
    # Add Label
    - name: Add Label
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: "Download in Comments"
        number: ${{ github.event.pull_request.number }}${{ github.event.inputs.PR }}