name: Build
env:
  SLN_PATH: Source/
on:
  workflow_dispatch:
    inputs:
      PR:
        description: PR Number
        required: true
  pull_request_target:
    branches: [ master, Development, staging ]

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Setup dot net
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x    

    # Build artifact
    - name: Building
      run: |
        dotnet restore ${{ env.SLN_PATH }}
        dotnet build ${{ env.SLN_PATH }} --configuration Debug --no-restore
    
    # Upload artifact
    - name: Upload Mod Files
      uses: actions/upload-artifact@v2
      with:
        name: build-combatrealism
        path: |
          About/
#           Assemblies/
#           Defs/
#           Ideology/
#           Languages/
#           Media/
#           Patches/
#           Royalty/
#           Sounds/
#           Textures/
#           Source/
#           LoadFolders.xml

    # Install Node 12
    - uses: actions/setup-node@v1
      with:
        version: 12    
    - run: npm install @octokit/action

    - name: Getting artifact Urls
      id: get_artifact
      uses: kbatbouta/artifact-comment@v1.2.2
#       run: node .github/actions/get-artifact.js
      with:
        run-id: ${{ github.run_id }}       
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}${{ github.event.inputs.PR }}
        body: |
          You can download the rebuilt assembly for this PR here: ${{ steps.get_artifact.outputs.urls }}

    - name: Add Label
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: "Download in Comments"
        number: ${{ github.event.pull_request.number }}${{ github.event.inputs.PR }}
