name: Build-Release
env:
  SLN_PATH: Source/
on:    
  release:
    types:
      - published

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Installing Dependencies
      run: dotnet restore ${{ env.SLN_PATH }}

    - name: Building Mod
      run: dotnet build ${{ env.SLN_PATH }} --configuration Debug --no-restore
    
    - name: Packaging
      run: |
          mkdir CombatRealism
          cp -r Assemblies/ About/ Defs/ Languages/ Patches/ Royalty/ Ideology/ Sounds/ Textures/ LoadFolders.xml README.md SupportedThirdPartyMods.md CombatRealism
          zip -9 -r CombatRealism.zip CombatRealism        
    
    - name: Upload Package
      id: upload-package
      uses: actions/upload-release-asset@v1
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: CombatRealism.zip
        asset_name: CombatRealism-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/octet-stream

